import { QRCodeSVG } from 'qrcode.react';
import { toast } from 'react-toastify';
import { XMarkIcon, PrinterIcon, ArrowDownTrayIcon } from '@heroicons/react/24/outline';

interface QRCodeGeneratorProps {
  value: string;
  title: string;
  subtitle?: string;
  onClose: () => void;
}

const QRCodeGenerator = ({ value, title, subtitle, onClose }: QRCodeGeneratorProps) => {
  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      toast.error('Please allow popups to print');
      return;
    }

    const qrCodeSvg = document.getElementById('qr-code-svg')?.outerHTML;

    printWindow.document.write(`
      <html>
        <head>
          <title>Print QR Code - ${title}</title>
          <style>
            body {
              display: flex;
              flex-direction: column;
              align-items: center;
              justify-content: center;
              min-height: 100vh;
              margin: 0;
              padding: 20px;
              font-family: Arial, sans-serif;
            }
            .qr-container {
              text-align: center;
              border: 2px solid #000;
              padding: 30px;
              border-radius: 10px;
            }
            h1 {
              margin: 0 0 10px 0;
              font-size: 24px;
            }
            p {
              margin: 0 0 20px 0;
              color: #666;
              font-size: 14px;
            }
            .qr-code {
              display: inline-block;
              padding: 20px;
              background: white;
              border: 1px solid #ddd;
            }
            .info {
              margin-top: 20px;
              font-size: 12px;
              color: #888;
            }
            @media print {
              body {
                background: white;
              }
            }
          </style>
        </head>
        <body>
          <div class="qr-container">
            <h1>${title}</h1>
            ${subtitle ? `<p>${subtitle}</p>` : ''}
            <div class="qr-code">
              ${qrCodeSvg}
            </div>
            <div class="info">
              <p>Scan this QR code to view details</p>
              <p>Generated by LabTracker</p>
            </div>
          </div>
        </body>
      </html>
    `);

    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
      printWindow.close();
    }, 250);

    toast.success('Opening print dialog...');
  };

  const handleDownload = () => {
    const svg = document.getElementById('qr-code-svg');
    if (!svg) return;

    const svgData = new XMLSerializer().serializeToString(svg);
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    const img = new Image();

    canvas.width = 512;
    canvas.height = 512;

    img.onload = () => {
      ctx?.drawImage(img, 0, 0, 512, 512);
      canvas.toBlob((blob) => {
        if (!blob) return;
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.download = `qr-${title.replace(/\s+/g, '-').toLowerCase()}.png`;
        link.href = url;
        link.click();
        URL.revokeObjectURL(url);
        toast.success('QR Code downloaded!');
      });
    };

    img.src = 'data:image/svg+xml;base64,' + btoa(svgData);
  };

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className="bg-white dark:bg-gray-800 rounded-xl p-6 max-w-md w-full">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-2xl font-bold text-gray-900 dark:text-white">QR Code</h2>
          <button
            onClick={onClose}
            className="p-2 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg transition-colors"
          >
            <XMarkIcon className="w-6 h-6 text-gray-600 dark:text-gray-400" />
          </button>
        </div>

        <div className="text-center mb-6">
          <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-1">{title}</h3>
          {subtitle && (
            <p className="text-sm text-gray-600 dark:text-gray-400">{subtitle}</p>
          )}
        </div>

        <div className="flex justify-center mb-6 p-6 bg-white dark:bg-gray-900 rounded-lg">
          <QRCodeSVG
            id="qr-code-svg"
            value={value}
            size={256}
            level="H"
            includeMargin={true}
            bgColor="#ffffff"
            fgColor="#000000"
          />
        </div>

        <div className="grid grid-cols-2 gap-3">
          <button
            onClick={handleDownload}
            className="btn-secondary flex items-center justify-center"
          >
            <ArrowDownTrayIcon className="w-5 h-5 mr-2" />
            Download
          </button>
          <button
            onClick={handlePrint}
            className="btn-primary flex items-center justify-center"
          >
            <PrinterIcon className="w-5 h-5 mr-2" />
            Print
          </button>
        </div>

        <p className="mt-4 text-xs text-center text-gray-500 dark:text-gray-400">
          Scan this QR code with any QR scanner to access reagent details
        </p>
      </div>
    </div>
  );
};

export default QRCodeGenerator;
